name: Drive Downloader
on: workflow_dispatch

jobs:
  download_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rclone
        run: sudo apt-get install rclone -y

      - name: Setup Config
        run: |
          mkdir -p ~/.config/rclone
          # Das Secret wird hier sicher eingefÃ¼gt
          echo "${{ secrets.RCLONE_CONFIG_CONTENT }}" > ~/.config/rclone/rclone.conf

      - name: Download to Drive
        run: |
          curl -L "https://www.7-zip.org/a/7z2401-extra.7z" -o test.7z
          # Wir erzwingen die Nutzung der Config
          rclone copy test.7z mydrive:CloudDownloads --config ~/.config/rclone/rclone.conf -v
